name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Agent System
        - Crew Coordination
        - Video Generation
        - Video Upload
        - Scripts/Utilities
        - Tests
        - CI/CD
        - Documentation
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system crash, data loss)
        - High (major functionality broken)
        - Medium (feature partially broken)
        - Low (minor issue, workaround available)
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error '...'
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any relevant error logs or stack traces
      render: shell
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details
      value: |
        - OS: 
        - Python Version: 
        - Package Versions: 
      render: markdown
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
