name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Agent System
        - Crew Coordination
        - Video Generation
        - Video Upload
        - Scripts/Utilities
        - Tests
        - CI/CD
        - Documentation
        - New Component
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (blocking work)
        - High (important functionality)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm trying to do X but...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: I would like to...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
  
  - type: textarea
    id: examples
    attributes:
      label: Example Usage
      description: Show how you would use this feature
      placeholder: |
        ```python
        # Example code
        ```
      render: python
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
